global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'customer-service-monitor'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'customer-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          service: 'customer-service'
          environment: 'development'
    scrape_interval: 10s

  - job_name: 'account-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          service: 'account-service'
          environment: 'development'
    scrape_interval: 10s

  - job_name: 'transaction-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          service: 'transaction-service'
          environment: 'development'
    scrape_interval: 10s

  # Keycloak metrics
  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:8080']

  # Add your Quarkus application here when ready
  # - job_name: 'customer-service'
  #   metrics_path: '/q/metrics'
  #   static_configs:
  #     - targets: ['customer-service:8081']